# Generated by Django 5.0.1 on 2024-01-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_filamentconfiguration_filament_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamentconfiguration',
            name='filament_image',
            field=models.ImageField(default='None', upload_to='filament_images'),
            preserve_default=False,
        ),
    ]
